# Default values for pravega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

version: 0.7.0
zookeeperUri: example-client:2181

externalAccess:
  enabled: false
  type: LoadBalancer

serviceAccount:
  name: pravega-components

bookkeeper:
  image:
    repository: pravega/bookkeeper
  replicas: 3
  storage:
    className: standard
    ledgerVolumeRequest: 10Gi
    journalVolumeRequest: 10Gi
    indexVolumeRequest: 10Gi
  autoRecovery: true

pravega:
  image:
    repository: pravega/pravega
  controllerReplicas: 1
  segmentStoreReplicas: 1
  debugLogging: false
  cacheVolumeRequest: 2Gi
  storage:
    className: standard
  tier2: pravega-tier2
