apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  version: 0.4.0
  zookeeperUri: zk-client:2181

  # Security configurations for Pravega
  # See https://github.com/pravega/pravega/blob/master/documentation/src/docs/security/pravega-security-configurations.md
  tls:
    static:
      controllerSecret: "controller-pki"
      segmentStoreSecret: "segmentstore-pki"

  bookkeeper:
    image:
      repository: pravega/bookkeeper
    replicas: 3

    resources:
      requests:
        memory: "3Gi"
        cpu: "1000m"
      limits:
        memory: "5Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

    # Turns on automatic recovery
    # see https://bookkeeper.apache.org/docs/latest/admin/autorecovery/
    autoRecovery: true

    # To enable bookkeeper metrics feature, take codahale for example here.
    # See http://bookkeeper.apache.org/docs/4.7.0/admin/metrics/ for more metrics provider
    # See http://bookkeeper.apache.org/docs/4.7.0/reference/config/#statistics for metrics provider configuration details
    options:
      enableStatistics: "true"
      statsProviderClass: "org.apache.bookkeeper.stats.codahale.CodahaleMetricsProvider"
      codahaleStatsGraphiteEndpoint: "graphite.example.com:2003"
      # Default is 60
      codahaleStatsOutputFrequencySeconds: "30"

    # Pass the JVM options to Bookkeeper
    bookkeeperJVMOptions:
      memoryOpts: ["-Xms2g", "-XX:MaxDirectMemorySize=2g"]
      gcOpts: ["-XX:MaxGCPauseMillis=20"]
      gcLoggingOpts: ["-XX:NumberOfGCLogFiles=10"]
      extraOpts: []

  pravega:
    image:
      repository: pravega/pravega

    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "3Gi"
        cpu: "1000m"
      limits:
        memory: "5Gi"
        cpu: "2000m"

    # Turn on Pravega Debug Logging
    debugLogging: false

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2

#      ecs:
#        uri: http://10.247.10.52:9020
#        bucket: shared
#        root: "pravega/example"
#        namespace: pravega
#        credentials: ecs-credentials

#      hdfs:
#        uri: hdfs://10.240.10.52:8020/
#        root: /example
#        replicationFactor: 3

    # See https://github.com/pravega/pravega/blob/3f5b65084ae17e74c8ef8e6a40e78e61fa98737b/config/config.properties
    # for available configuration properties
    options:
      pravegaservice.containerCount: "4"
      pravegaservice.cacheMaxSize: "17179869184"
      pravegaservice.zkSessionTimeoutMs: "10000"
      attributeIndex.readBlockSize: "1048576"
      readIndex.storageReadAlignment: "1048576"
      durableLog.checkpointMinCommitCount: "300"
      bookkeeper.bkAckQuorumSize: "3"
      metrics.dynamicCacheSize: "100000"
      metrics.enableStatistics: "true"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      # The mount dir for secrets is /etc/secret-volume
      controller.auth.tlsEnabled: "true"
      controller.auth.tlsCertFile: "/etc/secret-volume/controller01.pem"
      controller.auth.tlsKeyFile: "/etc/secret-volume/controller01.key.pem"
      controller.rest.tlsKeyStoreFile: "/etc/secret-volume/controller01.jks"
      controller.rest.tlsKeyStorePasswordFile: "/etc/secret-volume/password"
      pravegaservice.enableTls: "true"
      pravegaservice.certFile: "/etc/secret-volume/segmentStore01.pem"
      pravegaservice.keyFile: "/etc/secret-volume/segmentStore01.key.pem"

    # Pass the JVM options to controller and segmentstore
    controllerJvmOptions: ["-XX:MaxDirectMemorySize=1g"]
    segmentStoreJVMOptions: ["-XX:MaxDirectMemorySize=1g"]