apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  zookeeperUri: example-client:2181

  bookkeeper:
    image:
      repository: pravega/bookkeeper
      tag: 0.3.2
      pullPolicy: IfNotPresent

    replicas: 3

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

    # Turns on automatic recovery
    # see https://bookkeeper.apache.org/docs/latest/admin/autorecovery/
    autoRecovery: true

    # To enable bookkeeper metrics feature
    # See http://bookkeeper.apache.org/docs/4.7.0/admin/metrics/ for more metrics provider
    options:
      enableStatistics: true
      statsProviderClass: org.apache.bookkeeper.stats.codahale.CodahaleMetricsProvider

  pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3

    # Turn on Pravega Debug Logging
    debugLogging: false

    image:
      repository: pravega/pravega
      tag: 0.3.2
      pullPolicy: IfNotPresent

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi

    # See https://github.com/pravega/pravega/blob/3f5b65084ae17e74c8ef8e6a40e78e61fa98737b/config/config.properties
    # for available configuration properties
    options:
      metrics.enableStatistics: "true"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2

#      ecs:
#        uri: http://10.247.10.52:9020
#        bucket: shared
#        root: "pravega/example"
#        namespace: pravega
#        credentials: ecs-credentials

#      hdfs:
#        uri: hdfs://10.240.10.52:8020/
#        root: /example
#        replicationFactor: 3

    options:
      pravegaservice.containerCount: 4
      pravegaservice.cacheMaxSize: 17179869184
      pravegaservice.zkSessionTimeoutMs: 10000
      attributeIndex.readBlockSize: 1048576
      readIndex.storageReadAlignment: 1048576
      durableLog.checkpointMinCommitCount: 300
      bookkeeper.bkAckQuorumSize: 4
      metrics.dynamicCacheSize: 100000
