apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  version: 0.7.0
  zookeeperUri: zk-client:2181

  # Security configurations for Pravega
  # See https://github.com/pravega/pravega/blob/master/documentation/src/docs/security/pravega-security-configurations.md
  tls:
    static:
      controllerSecret: "controller-pki"
      segmentStoreSecret: "segmentstore-pki"

  bookkeeperUri: "pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181,pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181,pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181"

  pravega:
    image:
      repository: pravega/pravega

    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "16Gi"
        cpu: "8000m"

    # Turn on Pravega Debug Logging
    debugLogging: false

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2

#      ecs:
#        configUri: http://10.247.10.52:9020?namespace=pravega
#        bucket: "shared"
#        prefix: "example"
#        credentials: ecs-credentials

#      hdfs:
#        uri: hdfs://10.240.10.52:8020/
#        root: /example
#        replicationFactor: 3

    # See https://github.com/pravega/pravega/blob/3f5b65084ae17e74c8ef8e6a40e78e61fa98737b/config/config.properties
    # for available configuration properties
    options:
      pravegaservice.containerCount: "4"
      pravegaservice.cacheMaxSize: "11811160064"
      pravegaservice.zkSessionTimeoutMs: "10000"
      attributeIndex.readBlockSize: "1048576"
      readIndex.storageReadAlignment: "1048576"
      durableLog.checkpointMinCommitCount: "300"
      bookkeeper.bkAckQuorumSize: "3"
      metrics.dynamicCacheSize: "100000"
      metrics.enableStatistics: "true"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      # The mount dir for secrets is /etc/secret-volume
      controller.auth.tlsEnabled: "true"
      controller.auth.tlsCertFile: "/etc/secret-volume/controller01.pem"
      controller.auth.tlsKeyFile: "/etc/secret-volume/controller01.key.pem"
      controller.rest.tlsKeyStoreFile: "/etc/secret-volume/controller01.jks"
      controller.rest.tlsKeyStorePasswordFile: "/etc/secret-volume/password"
      pravegaservice.enableTls: "true"
      pravegaservice.certFile: "/etc/secret-volume/segmentStore01.pem"
      pravegaservice.keyFile: "/etc/secret-volume/segmentStore01.key.pem"

    # Pass the JVM options to controller and segmentstore
    controllerJvmOptions: ["-XX:MaxDirectMemorySize=1g"]
    segmentStoreJVMOptions: ["-Xmx4g", "-XX:MaxDirectMemorySize=12g"]
