apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: "example"
  labels:
    app.kubernetes.io/name: "pravega-cluster"
spec:
  version: 0.9.0
  zookeeperUri: zookeeper-client:2181

  # Security configurations for Pravega
  # See https://github.com/pravega/pravega/blob/master/documentation/src/docs/security/pravega-security-configurations.md
  tls:
    static:
      controllerSecret: "controller-pki"
      segmentStoreSecret: "segmentstore-pki"

  bookkeeperUri: "bookkeeper-bookie-0.bookkeeper-bookie-headless.default.svc.cluster.local:3181,bookkeeper-bookie-1.bookkeeper-bookie-headless.default.svc.cluster.local:3181,bookkeeper-bookie-2.bookkeeper-bookie-headless.default.svc.cluster.local:3181"

  pravega:
    image:
      repository: pravega/pravega

    controllerReplicas: 1
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"

    segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

    # Turn on Pravega Debug Logging
    debugLogging: false

    longtermStorage:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2

#      ecs:
#        configUri: http://10.247.10.52:9020?namespace=pravega
#        bucket: "shared"
#        prefix: "example"
#        credentials: ecs-credentials

#      hdfs:
#        uri: hdfs://10.240.10.52:8020/
#        root: /example
#        replicationFactor: 3

    # See https://github.com/pravega/pravega/blob/3f5b65084ae17e74c8ef8e6a40e78e61fa98737b/config/config.properties
    # for available configuration properties
    options:
      pravegaservice.container.count: "4"
      pravegaservice.cache.size.max: "1073741824"
      pravegaservice.zk.connect.sessionTimeout.milliseconds: "10000"
      readindex.storageRead.alignment: "1048576"
      durablelog.checkpoint.commit.count.min: "300"
      bookkeeper.ack.quorum.size: "3"
      metrics.dynamicCache.size: "100000"
      metrics.statistics.enable: "true"
      metrics.statsD.connect.host: "telegraph.default"
      metrics.statsD.connect.port: "8125"
      # The mount dir for tls secrets is /etc/secret-volume
      controller.security.tls.enable: "true"
      controller.security.tls.server.certificate.location: "/etc/secret-volume/controller01.pem"
      controller.security.tls.server.privateKey.location: "/etc/secret-volume/controller01.key.pem"
      controller.security.tls.server.keyStore.location: "/etc/secret-volume/controller01.jks"
      controller.security.tls.server.keyStore.pwd.location: "/etc/secret-volume/password"
      pravegaservice.security.tls.enable: "true"
      pravegaservice.security.tls.server.certificate.location: "/etc/secret-volume/segmentStore01.pem"
      pravegaservice.security.tls.server.privateKey.location: "/etc/secret-volume/segmentStore01.key.pem"
      # The mount dir for auth secrets is /etc/auth-passwd-volume
      controller.security.auth.enable: "true"
      controller.security.pwdAuthHandler.accountsDb.location: "/etc/auth-passwd-volume/userdata.txt"
      controller.security.auth.delegationToken.signingKey.basis: "secret"
      autoScale.controller.connect.security.auth.enable: "true"
      autoScale.security.auth.token.signingKey.basis: "secret"
      pravega.client.auth.token: "YWRtaW46MTExMV9hYWFh"
      pravega.client.auth.method: "Basic"

    # Pass the JVM options to controller and segmentstore
    segmentStoreJVMOptions: ["-Xmx2g", "-XX:MaxDirectMemorySize=2g"]
    controllerjvmOptions: ["-XX:MaxDirectMemorySize=1g"]
