kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pravega-tier2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  zookeeperUri: zk-client:2181
  bookkeeper:
    replicas: 3
  pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3
    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
