{{- if .Values.externalAccess.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pravega-components.fullname" . }}
rules:
- apiGroups:
  - ""
  resources: 
  - nodes
  verbs:
  - get
{{- end }}
