{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-{{ template "pravegaOperator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "pravegaOperator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
