{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pravega-operator.fullname" . }}-{{ .Release.Namespace }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega-operator.commonLabels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "pravega-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
