
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pravegaclusters-pravega-pravega-io-v1beta1-pravegacluster
  failurePolicy: Fail
  name: vpravegacluster.kb.io
  rules:
  - apiGroups:
    - pravegaclusters.pravega.pravega.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pravegaclusters
  sideEffects: None
