apiVersion: v1
kind: ServiceAccount
metadata:
  name: pravega-operator
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-operator
rules:
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-operator
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - "*"
  verbs:
  - '*'
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-operator
subjects:
- kind: ServiceAccount
  name: pravega-operator
roleRef:
  kind: Role
  name: pravega-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-operator
subjects:
- kind: ServiceAccount
  name: pravega-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: pravega-operator
  apiGroup: rbac.authorization.k8s.io
