apiVersion: "pravega.pravega.io/v1beta1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  version: 0.9.0
  zookeeperUri: zookeeper-client:2181
  externalAccess:
    enabled: true
    type: LoadBalancer
  bookkeeperUri: "bookkeeper-bookie-0.bookkeeper-bookie-headless.default.svc.cluster.local:3181,bookkeeper-bookie-1.bookkeeper-bookie-headless.default.svc.cluster.local:3181,bookkeeper-bookie-2.bookkeeper-bookie-headless.default.svc.cluster.local:3181"
  pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi
    image:
      repository: pravega/pravega
      pullPolicy: IfNotPresent
    longtermStorage:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
