apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: {{ template "pravega.fullname" . }}
  labels:
    app.kubernetes.io/name: "pravega-cluster"
spec:
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  externalAccess:
    enabled: {{ .Values.externalAccess.enabled }}
    type: {{ .Values.externalAccess.type }}
  bookkeeperUri: {{ .Values.bookkeeperUri }}
  pravega:
    {{- if .Values.externalAccess.enabled }}
    controllerServiceAccountName: {{ .Values.serviceAccount.name }}
    segmentStoreServiceAccountName: {{ .Values.serviceAccount.name }}
    {{- end }}
    image:
      repository: {{ .Values.pravega.image.repository }}
    controllerReplicas: {{ .Values.pravega.controllerReplicas }}
    controllerResources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"
    segmentStoreReplicas: {{ .Values.pravega.segmentStoreReplicas }}
    segmentStoreResources:
      requests:
        memory: "3Gi"
        cpu: "1000m"
      limits:
        memory: "5Gi"
        cpu: "2000m"
    debugLogging: {{ .Values.pravega.debugLogging }}
    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.pravega.storage.className }}
      resources:
        requests:
          storage: {{ .Values.pravega.cacheVolumeRequest }}
    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: {{ .Values.pravega.tier2 }}
