apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pravegaclusters.pravega.pravega.io
spec:
  group: pravega.pravega.io
  names:
    kind: PravegaCluster
    listKind: PravegaClusterList
    plural: pravegaclusters
    singular: pravegacluster
  additionalPrinterColumns:
  - name: Members
    type: integer
    description: The number pravega members running
    JSONPath: .status.replicas
  - name: Ready Members
    type: integer
    description: The number pravega members ready
    JSONPath: .status.readyReplicas
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
