name: cert-manager
apiVersion: v1
version: v0.14.1
appVersion: v0.14.1
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/jetstack/cert-manager
