name: pravega-operator
version: latest
appVersion: latest
description: pravega operator Helm chart for Kubernetes
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator
icon: https://avatars3.githubusercontent.com/u/25698199
sources:
- https://github.com/pravega/charts/blob/master/pravega-operator
engine: gotpl
