{{- if .Values.externalAccess.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pravega-components.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - get
- apiGroups: 
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
{{- end }}
