## Default values for pravega-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.
---
global:
  # Specifies which namespace the Operator should watch for new ClusterResource
  # resources
  # Default: true == Watch ALL namespaces
  watchAllNamespaces: false
  registry: emccorp
image:
  repository: pravega-operator
  tag: 0.5.2-214-a3498ebe # rfw-update-this pravega-operator-docker-image
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account names and whether to create it.
serviceAccount:
  create: true
  name: pravega-operator

## Whether to create the CRD.
crd:
  create: false

testmode:
  ## Whether to enable test mode.
  enabled: true
  ## version of pravega that you wish to deploy
  ## mention the major version number
  ## eg. enter 0.8.0 if u wish to deploy version 0.8.0-2500.efe501a
  version: "0.10.0"

webhookCert:
  crt:
  key:
  ## Whether to generate the certificate or not.
  generate: false
  ## If false, the name of the pre-existing certificate needs to be provided.
  certName: selfsigned-cert
  secretName: selfsigned-cert-tls

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""

hooks:
  backoffLimit: 10
  image:
    repository: k8s-kubectl
    tag: v1.16.10 # rfw-update-this k8s-kubectl-docker-image
