## Default values for pravega-operator.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

image:
  repository: pravega/pravega-operator
  tag: 0.5.1
  pullPolicy: IfNotPresent

## Install RBAC roles and bindings.
rbac:
  create: true

## Service account names and whether to create it.
serviceAccount:
  create: true
  name: pravega-operator

## Whether to create the CRD.
crd:
  create: true

testmode:
  ## Whether to enable test mode.
  enabled: false
  ## version of pravega that you wish to deploy
  ## mention the major version number
  ## eg. enter 0.8.0 if u wish to deploy version 0.8.0-2500.efe501a
  version: ""

webhookCert:
  crt:
  key:
  ## Whether to generate the certificate or not.
  generate: false
  ## If false, the name of the pre-existing certificate needs to be provided.
  certName: selfsigned-cert
  secretName: selfsigned-cert-tls

## Specifies which namespace the Operator should watch over.
## An empty string means all namespaces.
watchNamespace: ""

hooks:
  backoffLimit: 10
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
